### ISSUE TITLE
Unable to open inversion solutions in UCERF3 faults plugin

### ISSUE THREAD

**Issue by chrisbc** [SCECcode/scec-vdo#1]
e.g. opening  opensha-ucerf3/test/resources/scratch/UCERF3/utils/testAlpineVernonInversion.zip

we get: 

```
log4j:WARN No appenders could be found for logger (org.scec.vtk.tools.plugins.Plugins).
log4j:WARN Please initialize the log4j system properly.
****************ADDED PLUGIN: Political Boundaries
/home/chrisbc/DEV/GNS/opensha/scec-vdo/data/Grid/California.grat
****************ADDED PLUGIN: Graticule
****************ADDED PLUGIN: Drawing Tools
LayerID: org.scec.vdo.politicalBoundaries
LayerID: org.scec.vdo.graticulePlugin
LayerID: org.scec.vdo.drawingToolsPlugin
pluginLayerid: org.scec.vdo.politicalBoundaries should be equivalent to: org.scec.vdo.politicalBoundaries
pluginLayerid: org.scec.vdo.graticulePlugin should be equivalent to: org.scec.vdo.graticulePlugin
pluginLayerid: org.scec.vdo.drawingToolsPlugin should be equivalent to: org.scec.vdo.drawingToolsPlugin
/home/chrisbc/DEV/GNS/opensha/scec-vdo/data ? true
****************ADDED PLUGIN: UCERF3 Fault System Ruptures Plugin
java.lang.NullPointerException
	at scratch.UCERF3.FaultSystemRupSet.getNumRuptures(FaultSystemRupSet.java:218)
	at scratch.UCERF3.FaultSystemRupSet.setClusterRuptures(FaultSystemRupSet.java:836)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.<init>(InversionFaultSystemRupSet.java:222)
	at scratch.UCERF3.utils.FaultSystemIO.loadRupSetAsApplicable(FaultSystemIO.java:471)
```

NB this looks like it might be the same issue we fixed a little while ago in `public class InversionFaultSystemRupSet` where init() needed to be called in proper sequence (around line 225 - 228). In this case getNumRuptures would raise NullPointer because mags[] was not yet set.

@kevinmilner I can't see where how the **opensha.jar** is built for scec-vdo. Is it possible that this jar just needs to be updated??

**Comment by kevinmilner** [comment]
Yeah it was indeed that issue that you fixed previously. I updated the jar, and confirmed that it now works to load that test solution.
